version: '3'

services:
    dev-symfony-nginx:
        build:
            context: ./etc/docker/development
            dockerfile: nginx.docker
        volumes:
            - .:/app
        depends_on:
            - dev-symfony-php-fpm
            - test-symfony-postgres
        ports:
            - "8080:80"

    dev-symfony-php-fpm:
        build:
            context: ./etc/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - .:/app
        depends_on:
            - dev-symfony-mongo
            - dev-symfony-postgres
            - test-symfony-postgres
            - dev-symfony-mysql
            - dev-symfony-redis
        environment:
            - XDEBUG_CONFIG=remote_enable=1 remote_mode=req remote_port=9001 idekey=phpstorm remote_connect_back=0
            - PHP_IDE_CONFIG=serverName=Docker

    dev-symfony-php-cli:
        build:
            context: ./etc/docker/development
            dockerfile: php-cli.docker
        volumes:
            - .:/app
            - composer:/root/.composer/cache
        depends_on:
            - dev-symfony-mongo
            - dev-symfony-postgres
            - test-symfony-postgres
            - dev-symfony-mysql
            - dev-symfony-redis

    dev-symfony-postgres:
        image: postgres:14.2-alpine
        volumes:
            - dev-symfony-postgres:/var/lib/postgresql
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54320:5432"

    test-symfony-postgres:
        image: postgres:14.2-alpine
        volumes:
            - test-symfony-postgres:/var/lib/postgresql
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app_test
        ports:
            - "54321:5432"

    dev-symfony-mysql:
        image: mysql:8.0.28
        working_dir: /app
        volumes:
            - persistent:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=secret
        ports:
            - "33060:3306"

    dev-symfony-mongo:
        image: mongo:5
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db:rw,noexec,nosuid,size=2G
        command: --smallfiles --noprealloc --nojournal

    dev-symfony-node-watch:
        image: node:17-alpine
        volumes:
            - .:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"

    dev-symfony-node:
        image: node:17-alpine
        volumes:
            - .:/app
        working_dir: /app

    dev-symfony-redis:
        image: redis:6.0.9
        volumes:
            - dev-symfony-redis:/data
        ports:
            - "63790:6379"

volumes:
    dev-symfony-postgres:
    test-symfony-postgres:
    dev-symfony-mysql:
    dev-symfony-redis:
    composer:
    persistent:
