parameters:
    app.env: '%env(APP_ENV)%'

services:
    _defaults:
        autowire: true

    Fixtures\:
        resource: '../database/fixtures/**/*Fixture.php'
        tags: ['doctrine.fixture.orm']
