parameters:
    app.env: '%env(APP_ENV)%'

services:
    _defaults:
        autowire: true

    Tests\_data\Fixtures\:
        resource: '../tests/_data/Fixtures/**/*Fixture.php'
        tags: ['doctrine.fixture.orm']
